/**
 * POST /api/log
 *
 * Logt zoekevents, feedback en escalaties.
 * In-memory voor de PoC — vervang door Supabase insert in productie.
 */

export type LogEvent = {
	id?: string
	event: 'search' | 'feedback' | 'escalation'
	timestamp: string
	query?: string
	postcode?: string
	itemId?: string
	itemTitle?: string
	fraction?: string
	source?: string
	matchPercentage?: number
	feedback?: 'up' | 'down'
	layer?: number
	resultsCount?: number
	topMatch?: string | null
	topMatchPercentage?: number | null
	message?: string
	resolved?: boolean
	resolvedFraction?: string
	resolvedNote?: string
	resolvedAt?: string
	[key: string]: unknown
}

function daysAgo(n: number, hour = 10, minute = 0): string {
	const d = new Date()
	d.setDate(d.getDate() - n)
	d.setHours(hour, minute, 0, 0)
	return d.toISOString()
}

export const eventLog: LogEvent[] = [
	{
		event: 'search',
		timestamp: daysAgo(6, 9, 12),
		query: 'cola blik',
		postcode: '2000',
		resultsCount: 3,
		topMatch: 'Drankblikje',
		topMatchPercentage: 94,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(6, 9, 45),
		query: 'wijnfles',
		postcode: '1000',
		resultsCount: 2,
		topMatch: 'Glazen fles',
		topMatchPercentage: 89,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(6, 11, 3),
		query: 'autoband',
		postcode: '9000',
		resultsCount: 1,
		topMatch: 'Autoband',
		topMatchPercentage: 91,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(6, 14, 20),
		query: 'pampers',
		postcode: '2000',
		resultsCount: 1,
		topMatch: 'Luier',
		topMatchPercentage: 85,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(6, 16, 55),
		query: 'oud gsm',
		postcode: '',
		resultsCount: 2,
		topMatch: 'Kleine elektrische toestellen',
		topMatchPercentage: 72,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(5, 8, 30),
		query: 'nespresso capsule',
		postcode: '3000',
		resultsCount: 1,
		topMatch: 'Nespresso-capsule',
		topMatchPercentage: 97,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(5, 11, 0),
		query: 'wasmachine oud',
		postcode: '9000',
		resultsCount: 1,
		topMatch: 'Groot elektrisch toestel',
		topMatchPercentage: 88,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(5, 13, 45),
		query: 'lays zak',
		postcode: '2000',
		resultsCount: 1,
		topMatch: 'Plastic folie of zak',
		topMatchPercentage: 76,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(5, 15, 22),
		query: 'zetel',
		postcode: '1000',
		resultsCount: 1,
		topMatch: 'Zetel of bank',
		topMatchPercentage: 99,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(5, 17, 8),
		query: 'vape wegwerp',
		postcode: '2060',
		resultsCount: 1,
		topMatch: 'Wegwerp e-sigaret',
		topMatchPercentage: 91,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(4, 9, 5),
		query: 'cola blik',
		postcode: '2000',
		resultsCount: 3,
		topMatch: 'Drankblikje',
		topMatchPercentage: 94,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(4, 10, 30),
		query: 'pizzadoos',
		postcode: '2000',
		resultsCount: 2,
		topMatch: 'Vuile pizzadoos',
		topMatchPercentage: 87,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(4, 11, 45),
		query: 'kurken wijnfles',
		postcode: '',
		resultsCount: 0,
		topMatch: null,
		topMatchPercentage: 0,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(4, 12, 10),
		query: 'kurken wijnfles',
		postcode: '',
		resultsCount: 0,
		topMatch: null,
		topMatchPercentage: 0,
		layer: 2,
	},
	{
		event: 'search',
		timestamp: daysAgo(4, 14, 0),
		query: 'red bull',
		postcode: '3500',
		resultsCount: 2,
		topMatch: 'Drankblikje',
		topMatchPercentage: 88,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(4, 15, 33),
		query: 'kaasschaaf',
		postcode: '9000',
		resultsCount: 0,
		topMatch: null,
		topMatchPercentage: 0,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(4, 16, 0),
		query: 'kaasschaaf',
		postcode: '9000',
		resultsCount: 0,
		topMatch: null,
		topMatchPercentage: 0,
		layer: 3,
	},
	{
		event: 'search',
		timestamp: daysAgo(3, 8, 15),
		query: 'yoghurt',
		postcode: '2000',
		resultsCount: 3,
		topMatch: 'Plastic potje yoghurt',
		topMatchPercentage: 99,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(3, 9, 20),
		query: 'cola blik',
		postcode: '1000',
		resultsCount: 3,
		topMatch: 'Drankblikje',
		topMatchPercentage: 94,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(3, 10, 45),
		query: 'batterij',
		postcode: '2000',
		resultsCount: 1,
		topMatch: 'Batterij',
		topMatchPercentage: 99,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(3, 12, 0),
		query: 'kerstboom',
		postcode: '2000',
		resultsCount: 1,
		topMatch: 'Kerstboom',
		topMatchPercentage: 99,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(3, 13, 30),
		query: 'oud tapijt',
		postcode: '9000',
		resultsCount: 1,
		topMatch: 'Tapijt',
		topMatchPercentage: 82,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(2, 8, 0),
		query: 'luier',
		postcode: '2000',
		resultsCount: 1,
		topMatch: 'Luier',
		topMatchPercentage: 99,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(2, 9, 30),
		query: 'monster energy',
		postcode: '1000',
		resultsCount: 2,
		topMatch: 'Drankblikje',
		topMatchPercentage: 86,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(2, 11, 15),
		query: 'oud laptop',
		postcode: '2000',
		resultsCount: 1,
		topMatch: 'Kleine elektrische toestellen',
		topMatchPercentage: 69,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(2, 13, 0),
		query: 'cola blik',
		postcode: '2000',
		resultsCount: 3,
		topMatch: 'Drankblikje',
		topMatchPercentage: 94,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(1, 9, 0),
		query: 'pizzadoos',
		postcode: '2018',
		resultsCount: 2,
		topMatch: 'Vuile pizzadoos',
		topMatchPercentage: 87,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(1, 10, 15),
		query: 'kurken wijnfles',
		postcode: '',
		resultsCount: 0,
		topMatch: null,
		topMatchPercentage: 0,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(1, 11, 0),
		query: 'aansteker',
		postcode: '2000',
		resultsCount: 0,
		topMatch: null,
		topMatchPercentage: 0,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(1, 12, 45),
		query: 'cola blik',
		postcode: '1000',
		resultsCount: 3,
		topMatch: 'Drankblikje',
		topMatchPercentage: 94,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(0, 8, 0),
		query: 'wijnfles',
		postcode: '2000',
		resultsCount: 2,
		topMatch: 'Glazen fles',
		topMatchPercentage: 89,
		layer: 1,
	},
	{
		event: 'search',
		timestamp: daysAgo(0, 9, 30),
		query: 'oud tv',
		postcode: '9000',
		resultsCount: 1,
		topMatch: 'Beeldscherm of televisie',
		topMatchPercentage: 78,
		layer: 1,
	},
	// Feedback
	{
		event: 'feedback',
		timestamp: daysAgo(5, 10, 15),
		query: 'cola blik',
		itemId: 'drinks-can',
		itemTitle: 'Drankblikje',
		fraction: 'PMD',
		source: 'search',
		matchPercentage: 94,
		feedback: 'up',
	},
	{
		event: 'feedback',
		timestamp: daysAgo(4, 14, 5),
		query: 'red bull',
		itemId: 'drinks-can',
		itemTitle: 'Drankblikje',
		fraction: 'PMD',
		source: 'search',
		matchPercentage: 88,
		feedback: 'up',
	},
	{
		event: 'feedback',
		timestamp: daysAgo(4, 15, 40),
		query: 'kaasschaaf',
		itemId: 'metal-object',
		itemTitle: 'Metalen voorwerp',
		fraction: 'Recyclagepark - metaal',
		source: 'ai',
		matchPercentage: 72,
		feedback: 'down',
	},
	{
		event: 'feedback',
		timestamp: daysAgo(3, 9, 25),
		query: 'yoghurt',
		itemId: 'plastic-yoghurt-pot',
		itemTitle: 'Plastic potje yoghurt',
		fraction: 'PMD',
		source: 'search',
		matchPercentage: 99,
		feedback: 'up',
	},
	{
		event: 'feedback',
		timestamp: daysAgo(2, 9, 35),
		query: 'monster energy',
		itemId: 'drinks-can',
		itemTitle: 'Drankblikje',
		fraction: 'PMD',
		source: 'search',
		matchPercentage: 86,
		feedback: 'up',
	},
	{
		event: 'feedback',
		timestamp: daysAgo(2, 11, 20),
		query: 'oud laptop',
		itemId: 'small-electronics',
		itemTitle: 'Kleine elektrische toestellen',
		fraction: 'Recupel / recyclagepark',
		source: 'search',
		matchPercentage: 69,
		feedback: 'down',
	},
	{
		event: 'feedback',
		timestamp: daysAgo(1, 9, 5),
		query: 'pizzadoos',
		itemId: 'dirty-pizza-box',
		itemTitle: 'Vuile pizzadoos',
		fraction: 'Restafval',
		source: 'search',
		matchPercentage: 87,
		feedback: 'down',
	},
	{
		event: 'feedback',
		timestamp: daysAgo(0, 9, 35),
		query: 'wijnfles',
		itemId: 'glass-bottle',
		itemTitle: 'Glazen fles',
		fraction: 'Glasbol',
		source: 'search',
		matchPercentage: 89,
		feedback: 'up',
	},
	// Escalaties
	{
		id: 'esc-001',
		event: 'escalation',
		timestamp: daysAgo(5, 12, 0),
		query: 'kurken wijnfles',
		postcode: '2000',
		message: 'Ik heb een kurkje van een wijnfles. Waar moet dit in?',
		resolved: false,
	},
	{
		id: 'esc-002',
		event: 'escalation',
		timestamp: daysAgo(4, 11, 30),
		query: 'kaasschaaf',
		postcode: '9000',
		message: 'Metalen kaasschaaf met plastic handgreep. Waar hoort dit?',
		resolved: false,
	},
	{
		id: 'esc-003',
		event: 'escalation',
		timestamp: daysAgo(3, 16, 0),
		query: 'aansteker',
		postcode: '1000',
		message: 'Een lege aansteker van bic. Restafval of gevaarlijk afval?',
		resolved: true,
		resolvedFraction: 'KGA / recyclagepark',
		resolvedNote: 'Lege aansteker = KGA, bevat nog restgas',
		resolvedAt: daysAgo(2, 9, 0),
	},
	{
		id: 'esc-004',
		event: 'escalation',
		timestamp: daysAgo(2, 14, 0),
		query: 'speelgoedauto met batterij',
		postcode: '2018',
		message: 'Kapot speelgoedauto met ingebouwde batterij die niet los kan. Hoe sorteer ik dit?',
		resolved: false,
	},
	{
		id: 'esc-005',
		event: 'escalation',
		timestamp: daysAgo(1, 11, 0),
		query: 'kurken wijnfles',
		postcode: '3000',
		message: 'Kurken van champagneflessen, zijn dat PMD of restafval?',
		resolved: false,
	},
]

export default defineEventHandler(async (event) => {
	const body = await readBody(event)
	const entry: LogEvent = { ...body, timestamp: new Date().toISOString() }
	eventLog.push(entry)
	console.log('[sort-engine log]', JSON.stringify(entry))
	return { ok: true, total: eventLog.length }
})
